version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    networks:
      - symfony-network
    environment:
      APP_ENV: dev

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - symfony-network

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonymdp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-network

  webpack:
    image: node:18-alpine
    container_name: symfony_webpack
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm run watch
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  db_data:
